### ISSUE TITLE
Missing `config` file

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/serapis#5]
I encounter an import error:
```
ImportError: cannot import name 'config'
```

I'm guessing this module is missing as it contains sensitive information used for a specific setup? Do I need this Python module (i.e. is Serapis usually setup using arguments/a config file)?

**Comment by colin-nolan** [comment]
Example of `config.py` added in https://github.com/wtsi-hgi/serapis/commit/8591562b3b90bfb1aa2f3fada5d48a9a1f0d2a8d. 

The use of a Python module for configs is probably not the best solution though.

**Comment by irinaColgiu** [comment]
Solved, I committed also the config file 8591562b3b90bfb1aa2f3fada5d48a9a1f0d2a8d
